service: ec2-batch-control
# include extra setting
custom: ${file(./custom.yml)}

# setting lambda
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512 # optional, default is 1024. you can setting individual function.

  # you can overwrite defaults here
  stage: ${opt:stage} # production stage is [prod]
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:StartInstances
        - ec2:StopInstances
      Resource: "*"
  # environmentの値は、lambda function内で
  # process.env.{key}でアクセスする
  environment:
    stage: ${self:provider.stage}
    slack_webhook_url: ${self:custom.slack_webhook_url}
    ec2_instance_id: ${self:custom.ec2_instance_id}
    access_key: ${self:custom.access_key}
    secret_key: ${self:custom.secret_key}
    region: ${self:provider.region}

functions:
  ec2-start:
    handler: ec2-start.startHandler
    events:
      # 毎月1日の1時に実行(UTCなので -9hで設定)
     - schedule: cron(00 3 9 * ? *)
  ec2-halt:
    handler: ec2-halt.haltHandler
    events:
      # 毎月2日の23時に実行(UTCなので -9hで設定)
      - schedule: cron(10 3 9 * ? *)
